version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mlserve-network
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - ../.env
    volumes:
      - ../mlruns:/data
    networks:
      - mlserve-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"

  minio-create-bucket:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    container_name: minio-create-bucket
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do sleep 1; done;
      mc mb -p local/${MLFLOW_S3_BUCKET} || true;
      mc policy set public local/${MLFLOW_S3_BUCKET};
      "
    env_file:
      - ../.env
    networks:
      - mlserve-network

  init-db:
    build:
      context: ..
      dockerfile: infra/init-db/Dockerfile
    container_name: init-db
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ../.env
    networks:
      - mlserve-network

  mlflow:
    build:
      context: ..
      dockerfile: infra/mlflow/Dockerfile
    container_name: mlflow
    ports:
      - "${MLFLOW_PORT}:5000"
    env_file:
      - ../.env
    depends_on:
      init-db:
        condition: service_completed_successfully
      minio-create-bucket:
        condition: service_completed_successfully
    volumes:
      - ../mlruns:/mlflow/mlruns
    command: >
      mlflow server
      --backend-store-uri postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?options=-csearch_path=${MLFLOW_BACKEND_SCHEMA}
      --default-artifact-root s3://${MLFLOW_S3_BUCKET}
      --host 0.0.0.0
      --port 5000
    networks:
      - mlserve-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  api:
    build:
      context: ..
      dockerfile: infra/api/Dockerfile
    container_name: api
    ports:
      - "${API_PORT}:8000"
    env_file:
      - ../.env
    depends_on:
      mlflow:
        condition: service_healthy
    volumes:
      - ../:/app
    networks:
      - mlserve-network
    environment:
      - ENV=development
    command: >
      uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/docs || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  training:
    build:
      context: ..
      dockerfile: infra/train/Dockerfile
    container_name: training
    env_file:
      - ../.env
    depends_on:
      api:
        condition: service_healthy
    networks:
      - mlserve-network

networks:
  mlserve-network:
    driver: bridge

volumes:
  pgdata:
